FROM williamyeh/ansible:centos6
#FROM williamyeh/ansible:centos7
#FROM williamyeh/ansible:ubuntu14.04

# Add playbooks to the Docker image
ADD ansible /srv/example/
WORKDIR /srv/example

# Run Ansible to configure the Docker image
RUN ansible-playbook {{image}}.yml -i hosts/hosts.{{image}} -c local

# Other Dockerfile directives are still valid
#EXPOSE 22 3000 80
#ENTRYPOINT ["/usr/local/bin/apachectl", "-DFOREGROUND"]